#!/usr/bin/env python3
"""
Generate a formatted markdown report for PR test results.
"""

import json
import sys
from datetime import datetime
from typing import Any


def generate_report(data: dict) -> str:
    """Generate markdown report from test data."""

    pr_number = data.get("pr_number", "?")
    pr_title = data.get("pr_title", "Unknown PR")
    files = data.get("files", [])
    test_results = data.get("test_results", {})
    coverage = data.get("coverage", {})
    quality = data.get("quality", {})
    tests_generated = data.get("tests_generated", [])

    # Calculate summary stats
    passed = test_results.get("passed", 0)
    failed = test_results.get("failed", 0)
    total = passed + failed
    coverage_pct = coverage.get("percentage", 0)

    # Status emoji
    status = "✅" if failed == 0 else "❌"
    quality_grade = calculate_quality_grade(quality, failed)

    lines = [
        f"## 🤖 Automated Test Report for PR #{pr_number}",
        "",
        f"**PR Title:** {pr_title}",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "### 📊 Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| **Status** | {status} {'All Passed' if failed == 0 else 'Some Failed'} |",
        f"| **Tests Generated** | {len(tests_generated)} |",
        f"| **Test Results** | {passed}/{total} passed |",
        f"| **Coverage** | {coverage_pct}% |",
        f"| **Quality Grade** | {quality_grade} |",
        "",
        "### 📁 Files Analyzed",
        "",
        "| File | Status | Tests Added |",
        "|------|--------|-------------|",
    ]

    for f in files:
        status_emoji = "🆕" if f.get("status") == "added" else "📝"
        test_count = f.get("tests_added", 0)
        lines.append(f"| `{f['filename']}` | {status_emoji} {f['status'].title()} | {test_count} |")

    lines.extend([
        "",
        "### 🧪 Generated Tests",
        "",
    ])

    if tests_generated:
        for test in tests_generated:
            lines.extend([
                f"<details>",
                f"<summary><code>{test['path']}</code></summary>",
                "",
                f"```{test.get('language', 'python')}",
                test['content'],
                "```",
                "</details>",
                "",
            ])
    else:
        lines.append("*No new tests were generated for this PR.*")

    lines.extend([
        "",
        "### ✅ Test Results",
        "",
        "```",
        test_results.get("output", "No test output available"),
        "```",
        "",
    ])

    # Coverage section
    lines.extend([
        "",
        "### 📈 Coverage Report",
        "",
    ])

    if coverage.get("files"):
        lines.extend([
            "| File | Lines | Covered | Percentage |",
            "|------|-------|---------|------------|",
        ])
        for cov in coverage["files"]:
            lines.append(
                f"| `{cov['file']}` | {cov['total']} | {cov['covered']} | {cov['percentage']}% |"
            )
    else:
        lines.append(f"**Overall Coverage:** {coverage_pct}%")

    # Quality section
    lines.extend([
        "",
        "### 🔍 Code Quality",
        "",
        "| Check | Status | Issues |",
        "|-------|--------|--------|",
    ])

    quality_items = [
        ("Linting", quality.get("linting", {})),
        ("Formatting", quality.get("formatting", {})),
        ("Type Check", quality.get("type_check", {})),
    ]

    for name, q in quality_items:
        status = "✅" if q.get("passed", True) else "❌"
        issues = q.get("issues", 0)
        lines.append(f"| {name} | {status} | {issues} |")

    # Recommendations
    recommendations = generate_recommendations(data)
    if recommendations:
        lines.extend([
            "",
            "### 💡 Recommendations",
            "",
        ])
        for rec in recommendations:
            lines.append(f"- {rec}")

    lines.extend([
        "",
        "---",
        "*This report was automatically generated by the test-pull-request skill.*",
    ])

    return "\n".join(lines)


def calculate_quality_grade(quality: dict, failed_tests: int) -> str:
    """Calculate quality grade based on checks."""
    score = 100

    if failed_tests > 0:
        score -= 20 * failed_tests

    for check in ["linting", "formatting", "type_check"]:
        q = quality.get(check, {})
        if not q.get("passed", True):
            score -= 10
        score -= min(q.get("issues", 0), 10)

    if score >= 90:
        return "A 🟢"
    elif score >= 80:
        return "B 🟡"
    elif score >= 70:
        return "C 🟠"
    else:
        return "D 🔴"


def generate_recommendations(data: dict) -> list:
    """Generate recommendations based on results."""
    recs = []
    test_results = data.get("test_results", {})
    coverage = data.get("coverage", {})
    quality = data.get("quality", {})

    if test_results.get("failed", 0) > 0:
        recs.append("🚨 Fix failing tests before merging")

    if coverage.get("percentage", 0) < 80:
        recs.append(f"📉 Coverage at {coverage['percentage']}% - consider adding more tests for edge cases")

    for check in ["linting", "formatting", "type_check"]:
        q = quality.get(check, {})
        if not q.get("passed", True):
            recs.append(f"🔧 Fix {check} issues to improve code quality")

    if not data.get("tests_generated"):
        recs.append("📝 No tests generated - verify all new functionality is covered by existing tests")

    return recs


def main():
    # Read JSON data from stdin or file
    if len(sys.argv) > 1:
        with open(sys.argv[1]) as f:
            data = json.load(f)
    else:
        data = json.load(sys.stdin)

    report = generate_report(data)
    print(report)


if __name__ == "__main__":
    main()
